## ReplicaSet file -> it does not supports the condition
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myrs
spec:
  replicas: 3   # it order how many pods to i want to create
  selector:   #it helps to adopt the pods on the basis of labels
    matchExpressions: # it helps to adopt the pods on the basis of conditions
      - key: env
        operator: In
        values: ["dev", "test"] 
  template:   # it helps create the pods with the specified configuration
    metadata:
      labels: 
        env : test
    spec:
      containers:
      - name: mycontainer
        image: nginx
        ports:
        - containerPort: 80